name: sic
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.12.0
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.3
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - cryptography==46.0.3
      - distro==1.9.0
      - dotenv==0.9.9
      - filelock==3.20.0
      - fsspec==2025.12.0
      - google==3.0.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-speech==2.34.0
      - googleapis-common-protos==1.72.0
      - griffe==1.15.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - invoke==2.2.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keyboard==0.13.5
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - mcp==1.22.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - networkx==3.6
      - numba==0.62.1
      - numpy==2.2.6
      - openai==2.8.1
      - openai-agents==0.6.1
      - openai-whisper==20250625
      - opencv-python==4.12.0.88
      - paramiko==4.0.0
      - pillow==12.0.0
      - proto-plus==1.26.1
      - protobuf==6.33.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyaudio==0.2.14
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyjwt==2.10.1
      - pynacl==1.6.1
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pyturbojpeg==1.8.2
      - pywin32==311
      - redis==7.0.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rpds-py==0.29.0
      - rsa==4.9.1
      - scipy==1.16.3
      - scp==0.15.0
      - six==1.17.0
      - sniffio==1.3.1
      - social-interaction-cloud==2.1.7
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soupsieve==2.8
      - sse-starlette==3.0.3
      - starlette==0.50.0
      - sympy==1.14.0
      - tiktoken==0.12.0
      - torch==2.9.1
      - tqdm==4.67.1
      - types-requests==2.32.4.20250913
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - websockets==15.0.1
